#! /bin/sh

rm -rf ./chm
rm -rf ./config.*
rm -rf ./autom4te.cache
rm -rf ./src/Makevars
rm -rf ./src/Makedeps
rm -rf ./src/Makeconf
rm -rf ./src/*.dylib
rm -rf ./src/*.so
rm -rf ./src/*.o
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./src/*.a
rm -rf ./src/*.rc
rm -rf ./src/*.rds

find ./ -type f -name '*.o' -delete
find ./ -type f -name '*.mod' -delete

rm -rf ./src-*
rm -rf ./inst/etc*
rm -rf ./man/*.pdf
